<a href="https://colab.research.google.com/github/homerabbitsky/HelloAI/blob/main/assignment2_darkness.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from tensorflow.keras.datasets import mnist
np.set_printoptions(linewidth=np.inf)
#retval = mnist.load_data()
#X_train = retval[0][0]
#Y_train = retval[0][1]
#X_test = retval[1][0]
#Y_test = retval[1][1]

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()


11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
print(X_train.shape)
print(Y_train.shape)
print(X_train[0].shape)
print(Y_train[0].shape)
print(X_train[0])
print(Y_train[0])


(60000, 28, 28)
(60000,)
(28, 28)
()
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 2

In [ ]:
# first twn images
images = X_train[0:10]

In [ ]:
counts = [0]*10
for y in Y_train:
  counts[y] = counts[y]+1

print(counts)

#how many digits are in Y_train

[5923, 6742, 5958, 6131, 5842, 5421, 5918, 6265, 5851, 5949]


In [ ]:
#create function to calculate the darkness of a single image (only 28x28 images)

def calcDarkness(x):
  total = 0
  for r in range(28):
    for c in range(28):
      total = total + x[r][c]
  return total

In [ ]:
#test our darkness function
print(calcDarkness(X_train[1]))

darknesses = [0]*10
#loop through all the training images
for x, y in zip(X_train, Y_train):
  darkness = calcDarkness(x)
  darknesses [y] = darknesses[y] + darkness

darkness = [darknesstotal/counts[i] for i, darknesstotal in enumerate(darkness)]
print(darknesses)

31095


TypeError: ignored

In [ ]:
#randomized code

import random
images = random.sample(X_train,10)
for i in range(10):
    imgx = X_train[random.randint(0,len(X_train))]
    print(imgx)

TypeError: ignored