<a href="https://colab.research.google.com/github/homerabbitsky/HelloAI/blob/main/HelloAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Hello Python and AI
### this uses a markdown language



In [ ]:
print("Hello Python and AI")

a = 1
b = 2

print(f"{a} + {b} = {a+b}")

def sayHello(msg):
  print(f"Hello: {msg}")

sayHello(3)
sayHello(True)
sayHello(3.141519)
sayHello(" a string")
sayHello([0, 1, 2, 3])

Hello Python and AI
1 + 2 = 3
Hello: 3
Hello: True
Hello: 3.141519
Hello:  a string
Hello: [0, 1, 2, 3]


In [ ]:
sayHello("still alive!")

Hello: still alive!


In [ ]:
import torch
import numpy
import matplotlib.pyplot as plt

x = torch.ones(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
import numpy as np


In [ ]:
numpy.array()

numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

import numpy as np
#creating 1-dimensional arrays
#creating python list
list_1 = [3,2,7]
arr_1 = np.array(list_1,dtype=np.int16)
print(arr_1)
#or 
arr_1=np.array([3,2,7])
print(arr_1)
output:
[3 2 7]
#creating array of complex number
arr_complex = np.array([1, 2, 3], dtype = complex)
print(arr_complex)
output:
[1.+0.j 2.+0.j 3.+0.j]

TypeError: ignored

In [ ]:
#creating two-dimensionsal array
list_m = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] #nested lists
arr_m = np.array(list_m,dtype=np.int16)
print(arr_m)
output:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

SyntaxError: ignored

In [ ]:
#Creating an array of all zeros
arr_0 = np.zeros((2,2))  
print(arr_0)
output:
[[0. 0.]
 [0. 0.]]

SyntaxError: ignored

In [ ]:
# Creating an array of all ones
arr_1= np.ones((1,2))    
print(arr_1)
output:
[[1. 1.]]

SyntaxError: ignored

In [ ]:
# Creating a constant array
arr_c = np.full((2,2), 7) 
print(arr_c)
output:
[[7 7]
 [7 7]]

SyntaxError: ignored

In [ ]:
arr_L = np.linspace(0, 5,7)
print(arr_L)
output:
[0.         0.83333333 1.66666667 2.5        3.33333333 4.16666667
 5.        ]
#observe here dtype('float64')

SyntaxError: ignored

In [ ]:
arr_a=np.arange(1, 10,1)
print(arr_a)
output:
[1 2 3 4 5 6 7 8 9]
#here dtype('int32')

SyntaxError: ignored

In [ ]:
arr_r = np.random.random((2,2))  
print(arr_r)
output:                 
[[0.05736758 0.58044299]
 [0.57759937 0.85564153]]

In [ ]:
arr_1= np.random.randint(10,100,7)  
print(arr_1)
output:                     
[43 15 15 62 31 88 69]

In [ ]:
arr_n= np.random.randn(10)  
print(arr_n) 
output:
[ 0.71586489 -0.2929509   0.1952457   1.07499362  0.08089464 -0.18440427
 -0.00194278  0.2594934   1.8713812  -0.76195258]

In [ ]:
arr_I = np.eye(2)         Create a 2x2 identity matrix
print(arr_I)
output:
[[1. 0.]
 [0. 1.]]

In [ ]:
#converting list to ndarray 
import numpy as np
x = [1,2,3] 
a = np.asarray(x) 
print (a)
output:
[1 2 3]
# ndarray from tuple 
x_1 = (1,2,3) 
a_1 = np.asarray(x_1) 
print (a_1)
output:
[1 2 3]
# ndarray from list of tuples 
import numpy as np
x_2 = [(1,2,3),(4,5)] 
a_2 = np.asarray(x_2) 
print (a_2)
output:
[(1, 2, 3) (4, 5)]

In [ ]:
arr.shape :

SyntaxError: ignored

In [ ]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr.shape)
output: 
(2, 3)
#resizing the above array
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)
output:
[[1 2]
 [3 4]
 [5 6]]
or 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)
Output:
[[1, 2] 
 [3, 4] 
 [5, 6]]

In [ ]:
arr.size :

In [ ]:
import numpy as np 
x = np.array([[3,2,1],[4,6,1]]) 
print(x.size)
output:
6

In [ ]:
arr.itemsize:

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.itemsize
output:
4

In [ ]:
arr.ndim:

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.ndim
output:
2

In [ ]:
type(arr)

In [ ]:
#for example -
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr)
output: 
[[1,2,3]
 [4,5,6]]
type(arr)
output:
numpy.ndarray

In [ ]:
arr.dtype:

In [ ]:
#for example -
print(arr.dtype)
output:
int32

In [ ]:
arr_r = np.random.random((2,2))  
print(arr_r)
output:                 
[[0.05736758 0.58044299]
 [0.57759937 0.85564153]]

In [ ]:
arr_1= np.random.randint(10,100,7)  
print(arr_1)
output:                     
[43 15 15 62 31 88 69]

In [ ]:
arr_n= np.random.randn(10)  
print(arr_n) 
output:
[ 0.71586489 -0.2929509   0.1952457   1.07499362  0.08089464 -0.18440427
 -0.00194278  0.2594934   1.8713812  -0.76195258]

In [ ]:
arr_I = np.eye(2)         Create a 2x2 identity matrix
print(arr_I)
output:
[[1. 0.]
 [0. 1.]]

In [ ]:
#converting list to ndarray 
import numpy as np
x = [1,2,3] 
a = np.asarray(x) 
print (a)
output:
[1 2 3]
# ndarray from tuple 
x_1 = (1,2,3) 
a_1 = np.asarray(x_1) 
print (a_1)
output:
[1 2 3]
# ndarray from list of tuples 
import numpy as np
x_2 = [(1,2,3),(4,5)] 
a_2 = np.asarray(x_2) 
print (a_2)
output:
[(1, 2, 3) (4, 5)]

In [ ]:
arr.shape :

In [ ]:
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr.shape)
output: 
(2, 3)
#resizing the above array
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print (a)
output:
[[1 2]
 [3 4]
 [5 6]]
or 
a = np.array([[1,2,3],[4,5,6]]) 
b = a.reshape(3,2) 
print (b)
Output:
[[1, 2] 
 [3, 4] 
 [5, 6]]

In [ ]:
arr.size :

In [ ]:
import numpy as np 
x = np.array([[3,2,1],[4,6,1]]) 
print(x.size)
output:
6

In [ ]:
arr.itemsize:

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.itemsize
output:
4

In [ ]:
arr.ndim:

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.ndim
output:
2

In [ ]:
type(arr)

In [ ]:
#for example -
import numpy as np 
arr = np.array([[1,2,3],[4,5,6]]) 
print (arr)
output: 
[[1,2,3]
 [4,5,6]]
type(arr)
output:
numpy.ndarray

In [ ]:
#for example -
print(arr.dtype)
output:
int32

In [ ]:
arr.nbytes:

In [ ]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.nbytes
output:
24

In [ ]:
import numpy as np
arr = np.arange(10)
print(arr)
output:
[0 1 2 3 4 5 6 7 8 9]
#Example-1
print(arr[7])
or 
print(arr[-3])
output:
7
#Example-2
print(arr[0:5])
or 
print(arr[0:-4])
output:
[0 1 2 3 4 5]
#Example-3
print(arr[-4:-1])
output:
[6 7 8]

In [ ]:
arr[lower:upper:step]

In [ ]:
import numpy as np 
arr = np.arange(10)
#Slicing single element
slice_arr = arr[2] 
print (slice_arr)
output:
[2]
#Slicing elements in between indexes
print (arr[2:5])
or
print (arr[-8:-5]) #using negative index
output:
[2,3,4]
#using slice(lower,upper,step) function
s = slice(2,7,2) 
print (arr[s])
output:
[2,4,6]
or
slice_arr = arr[2:7:2] 
print (slice_arr)
output:
[2,4,6]

In [ ]:
x= np.array([11,12,13,14,15])
print(np.take(x, [0, 3,4]))
output:
[11 14 15]

In [ ]:
arr=np.arange(10)
#Example-1
print(arr[:5])
output:
[0 1 2 3 4]
#Example-2
print(arr[5:])
output:
[5 6 7 8 9]
#Example-3
print(arr[::2])
output:
[0 2 4 6 8]

In [ ]:
import numpy as np 
arr = np.array([[1,2,3],[3,4,5],[4,5,6]])
print (arr)
output:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
#Slicing first row
print (arr[0:1])
output:
[[1 2 3]]
#slicing last 2 rows
print (arr[1:])
output:
[[3 4 5]
 [4 5 6]]
#slicing three rows and first column
print (arr[0:3,0:1])
output:
[[1]
 [3]
 [4]]
#slicing 4 from above array
print (arr[1:2,1:2])
output:
[[4]] 

In [ ]:
numpy.stack(arrays,axis)

In [ ]:
import numpy as np
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([2, 3, 4])
arr_stack=np.stack((arr_1,arr_2),axis=0)
print(arr_stack)
print(arr_stack.shape)
output:
[[1 2 3]
 [2 3 4]]
(2,3)
arr_stack=np.stack((arr_1,arr_2),axis=1)
print(arr_stack)
print(arr_stack.shape)
output:
[[1 2]
 [2 3]
 [3 4]]
(3,2)

In [ ]:
numpy.vstack(tup)

In [ ]:
numpy.hstack(tup)

In [ ]:
# Generate random arrays
arr_1 = np.random.randint(10, size=(2, 2))
print(" arr_1\n", arr_1)
arr_2 = np.random.randint(10, size=(2, 2))
print(" arr_2\n", arr_2)
output:
 arr_1
 [[0 2]
 [7 6]]
 arr_2
 [[3 7]
 [1 4]]
# Stack arr_2 under arr_1
a=np.vstack((arr_1, arr_2))
print(a)
output:
[[0 2]
 [7 6]
 [3 7]
 [1 4]]
# Stacking  horizontally
b=np.hstack((arr_1, arr_2))
print(b)
output:
[[0 2 3 7]
 [7 6 1 4]]


In [ ]:
numpy.dstack(tup)

In [ ]:
#continuing above commands
#stacking depth wise
c=np.dstack((arr_1, arr_2))
print(c)
output:
[[[0 3]
 [2 7]]
[[7 1]
 [6 4]]]

In [ ]:
numpy.column_stack(tup)

In [ ]:
numpy.row_stack(tup)

In [ ]:
# row_stack()
a=np.row_stack((arr_1, arr_2))
print(a)
output:
[[0 2]
 [7 6]
 [3 7]
 [1 4]]
# column_stack()
b=np.column_stack((arr_1, arr_2))
print(b)
output:
[[0 2 3 7]
 [7 6 1 4]]

In [ ]:
numpy.split(array,Indices_or_sections,axis)

In [ ]:
x = np.arange(9.0)
np.split(x, 3)
output:
[array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.,  8.])]

In [ ]:
numpy.array_split(array,Indices_or_sections,axis)

In [ ]:
x = np.arange(8.0)
np.array_split(x, 3)
output:
[array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
x = np.arange(7.0)
np.array_split(x, 3)
output:
[array([0.,  1.,  2.]), array([3.,  4.]), array([5.,  6.])]
#all splitted arrays are not equal in size

In [ ]:
numpy.hsplit(array,Indices_or_sections,axis)

In [ ]:
arr_1 = np.arange(16.0).reshape(4, 4)
 arr_1
output:
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
np.hsplit(arr_1, 2)
output:
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11.],
       [14.,  15.]])]
np.hsplit(arr_1, np.array([3, 6]))
output:
[array([[ 0.,   1.,   2.],
       [ 4.,   5.,   6.],
       [ 8.,   9.,  10.],
       [12.,  13.,  14.]]),
 array([[ 3.],
       [ 7.],
       [11.],
       [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [ ]:
numpy.vsplit(array,Indices_or_sections,axis)

In [ ]:
arr_1= np.arange(16.0).reshape(4, 4)
arr_1
output:
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
np.vsplit(arr_1, 2)
output:
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
np.vsplit(arr_1, np.array([3, 6]))
output:
[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]

In [ ]:
import numpy as np
arr_3 = np.array([1, 2, 3, 4])
arr_4 = np.array([2, 4, 6, 8])
# Add values
print(arr_3 + arr_4)
or
np.add(arr_3 ,arr_4)
output:
[ 3,  6,  9, 12]
# Subtract
print(arr_3 - arr_4)
or
np.subtract(arr_3 ,arr_4)
output:
[-1, -2, -3, -4]
# Multiply
print(arr_3 * arr_4)
or
np.multiply(arr_3 ,arr_4)
output:
[ 2,  8, 18, 32]
# Divide
print(arr_3 / arr_4)
or
np.divide(arr_3,arr_4)
output:
[0.5, 0.5, 0.5, 0.5]

In [ ]:
#Random 2 by 3 digit 2D array between 0 to 100
arr_6 =np.random.randint(100, size=(2, 3))
print(arr_6)
output:
[[62, 96, 50],
 [87, 26, 42]]
# Sum of values in array
a=arr_3.sum()
print(a)
output:
10
# Sum columns
c=arr_6.sum(axis=0)
print(c)
output:
[149 122  92]
# Cumulative sum of rows
b=arr_6.cumsum(axis=1)
print(b)
output:
[[ 62 158 208]
 [ 87 113 155]]

In [ ]:
arr=np.array([[62, 96, 50],
       [87, 26, 42]])
# Min of each row
print(arr.min(axis=1))
output:
[52  1]
# Max of each column
print(arr.max(axis=0))
output:
[87 96 50]

In [ ]:
print(np.absolute([-1, -2]))
output:
[1, 2]

In [ ]:
arr_5 = np.array([[1, 2], [3, 4]])
arr_6 = np.array([[2, 4], [6, 9]])
# Return values in 1st array to powers defined in 2nd array
print(np.power(arr_5, arr_6))
output:
[[     1,     16],
      [   729, 262144]]
arr_3 = np.array([1, 2, 3, 4])
#Square Root
print(np.sqrt(arr_3))
output:
[1.         1.41421356 1.73205081 2.        ]
#Cube Root
print(np.cbrt(arr_3))
output:
[1.         1.25992105 1.44224957 1.58740105]

In [ ]:
arr_3 = np.array([1, 2, 3, 4])
#Exponential of all elements in array
print(np.exp(arr_3))
output:
[ 2.71828183  7.3890561  20.08553692 54.59815003]

In [ ]:
print(np.log(arr_3))
output:
[0.         0.69314718 1.09861229 1.38629436]
print(np.log2(arr_3))
output:
[0.        1.        1.5849625 2.       ]
print(np.log10(arr_3))
output:
[0.         0.30103    0.47712125 0.60205999]

In [ ]:
print(np.gcd.reduce([9, 12, 15]))
output:
3

In [ ]:
print(np.lcm.reduce([9, 12, 15]))
output:
180

In [ ]:
# Round down
print(np.floor([1.2, 2.5]))
output:
[1. 2.]
# Round up
print(np.ceil([1.2, 2.5]))
output:
[2. 3.]

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
# Generate array of 200 values between -pi & pi
t_arr = np.linspace(-2*np.pi, 2*np.pi, 200)
fig = plt.figure()
ax = plt.axes()
ax.grid(color='black', linestyle='-', linewidth=2,alpha=0.1)
# Plotting Sin(X)
plt.plot(t_arr, np.sin(t_arr),color='black') # SIN
plt.title("sin(x)")
# Display plot
plt.show()

In [ ]:
#plotting cos(x)
plt.plot(t_arr, np.cos(t_arr),color='darkorange') # COS
plt.title("cos(x)")

In [ ]:
#plotting tan(x)
plt.plot(t_arr, np.tan(t_arr),color='skyblue') # TAN
plt.title("tan(x)")

In [ ]:
plt.plot(t_arr, np.sin(t_arr),color='black',label='sin(x)') # SIN
plt.plot(t_arr, np.cos(t_arr),color='darkorange',label='cos(x)') # COS
plt.plot(t_arr, np.tan(t_arr),color='skyblue',label='tan(x)') # TAN
plt.legend(loc='best')
plt.show()

In [ ]:
# Provides inverse 
print(np.arcsin(1))
print(np.arccos(1))
print(np.arctan(0))
output:
1.5707963267948966
0.0
0.0

In [ ]:
# Radians to degrees
print(np.rad2deg(np.pi))
output:
180.0
# Degrees to radians
print(np.deg2rad(180))
output:
3.141592653589793

In [ ]:
arr_1 = np.arange(1, 6)
print(arr_1)
output:
[1 2 3 4 5]
#mean
print(np.mean(arr_1))
output:
3.0
#median
print(np.median(arr_1))
output:
3.0
#average
print(np.average(arr_1))
output:
3.0
# Standard Deviation
print(np.std([4, 6, 3, 5, 2])) 
output:
1.4142135623730951
#variance
print(np.var([4, 6, 3, 5, 2]))
output:
2.0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
v3=[ 4, 6 , 7 ]
v2= [ 4 ,7 ,9 ]
v3t = np.transpose(v3)
print(v3t)
output:
[ 4, 6 , 7 ]

In [ ]:
#taking 2 vectors of same dimention
v1 = np.array([ 2 ,6 ])
v2 = np.array([ 5 ,7 ])
v3 = v1+v2 #Addition
print(v3)
output:
[ 7, 13]
v4 = v2-v1 #Subtraction
print(v4)
output:
[3, 1]

In [ ]:
# VECTOR SCALAR PRODUCT
v1 = np.array([ 9 ,2 ]) 
c= 0.7
v2= c*v1
print(v2)
output:
[6.3, 1.4]
# dot product 
v1 = np.array([ 4 ,3 ,9 ])
v2 = np.array([ 1 ,2 ,3 ])
#method 1
D_P1 = sum( np.multiply(v1,v2)  )
print(D_P1)
output:
37
#method 2
D_P2 = np.dot( v1,v2 )
print(D_P2)
output:
37
#method 3
D_P3= np.matmul( v1,v2 )
print(D_P3)
output:
37

In [ ]:
# create vectors
w1 = [ 1, 3, 5 ]
w2 = [ 3, 4, 2 ]
w3 = np.multiply(w1,w2)
print(w3)
output:
[ 3 12 10]

In [ ]:
v1 = np.array([3,9,9])
v2 = np.array([2,3,4])
v3 = np.cross (v1,v2)
print (v3)
output:
[ 9  6 -9]

In [ ]:
#  vector 
v1 = np.array([ 3,4,6 ])
# example method 1
vl = np.sqrt( sum( np.multiply(v1,v1)) )
or
# method 2: take the norm
vl = np.linalg.norm(v1)
print(vl)
output:
7.810249675906654

https://medium.com/mlpoint/numpy-for-machine-learning-211a3e58b574